config/routes.rb
Naturesoft::Articles::Engine.routes.draw do
  namespace :backend, module: "backend", path: "backend/content" do
    resources :articles do
      collection do
        put "approve"
        put "disapprove"
        put "enable"
        put "disable"
        delete 'delete'
        get 'select2'
      end
    end
    resources :categories do
      collection do
        put "enable"
        put "disable"
        delete 'delete'
        get "select2"
      end
    end
  end
end

app/models/naturesoft/articles/application_record.rb
module Naturesoft::Articles
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/naturesoft/articles/article.rb
module Naturesoft::Articles
  class Article < ApplicationRecord
		mount_uploader :image_url, Naturesoft::Articles::ArticleUploader
		validates :title, :content, presence: true
		validates :image_url, presence: true
		validates :image_url, allow_blank: true, format: {
			with: %r{\.(gif|jpg|png)\Z}i,
			message: 'must be a URL for GIF, JPG or PNG image.'
		}
		
    belongs_to :user
    has_and_belongs_to_many :categories
    
    scope :ordered, -> { order('created_at desc') }
    
    def self.sort_by
      [
        ["Title","naturesoft_articles_articles.title"],
        ["Created At","naturesoft_articles_articles.created_at"]
      ]
    end
    
    def self.sort_orders
      [
        ["ASC","asc"],
        ["DESC","desc"]
      ]
    end
    
    def self.status
      [
        ["All",""],
        ["Active","true"],
        ["Inactive","false"]
      ]
    end
    
    #Filter, Sort
    def self.search(params)
      records = self.all
      
      #Search keyword filter
      if params[:keyword].present?
        params[:keyword].split(" ").each do |k|
          records = records.where("LOWER(CONCAT(naturesoft_articles_articles.title)) LIKE ?", "%#{k.strip.downcase}%") if k.strip.present?
        end
      end
      
      # for sorting
      sort_by = params[:sort_by].present? ? params[:sort_by] : "naturesoft_articles_articles.title"
      sort_orders = params[:sort_orders].present? ? params[:sort_orders] : "asc"
      records = records.order("#{sort_by} #{sort_orders}")
      
      return records
    end
    
    # change approve
    def approve
			update_columns(approved: true)
		end
    
    def disapprove
			update_columns(approved: false)
		end
    
    # change status
    def enable
			update_columns(status: "active")
		end
    
    def disable
			update_columns(status: "inactive")
		end
    
    # data for select2 ajax
    def self.select2(params)
			items = self.search(params)
			if params[:excluded].present?
				items = items.where.not(id: params[:excluded].split(","))
			end
			options = [{"id" => "nil", "text" => "none"}]
			options += items.map { |c| {"id" => c.id, "text" => c.title} }
			result = {"items" => options}
		end
    
    # get all articles
    def self.get_all_article
			Article.where(status: "active").where(approved: true)
		end
    
    # get recent posts/newest articles
    def self.get_recent_posts(num=5)
			Article.get_all_article.order("created_at desc").limit(5)
		end
    
    # get posts by category (module menus)
    def self.get_posts_for_category(params)
			records = Article.get_all_article.joins(:categories).where(naturesoft_articles_categories: {id: params[:cat_id]}).uniq
			return records
		end
    
    def get_tags
			tags.to_s.split(/[\,\;]/).select {|c| c.present? }
		end
    
    # Search for frontend
    def self.search_frontend(params)
      records = self.get_posts_for_category(params)
      
      #Search keyword filter
      if params[:key].present?
        params[:key].split(" ").each do |k|
          records = records.where("LOWER(CONCAT(naturesoft_articles_articles.title)) LIKE ?", "%#{k.strip.downcase}%") if k.strip.present?
        end
      end      
      return records
    end
    
  end
end

app/models/naturesoft/articles/articles_category.rb
module Naturesoft::Articles
  class ArticlesCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
  end
end

app/controllers/naturesoft/articles/admin/articles_controller.rb
module Naturesoft
  module Articles
    module Admin
      class ArticlesController < Naturesoft::Admin::AdminController
        before_action :set_article, only: [:show, :edit, :update, :approve, :disapprove, :enable, :disable, :destroy]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Article", naturesoft_articles.admin_articles_path
          add_breadcrumb "Articles", naturesoft_articles.admin_articles_path
        end
    
        # GET /articles
        def index
          @articles = Article.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("articles", "items_per_page"))
        end
    
        # GET /articles/1
        def show
        end
    
        # GET /articles/new
        def new
          @article = Article.new
          add_breadcrumb "New Article", nil,  class: "active"
        end
    
        # GET /articles/1/edit
        def edit
          add_breadcrumb "Edit Article", nil,  class: "active"
        end
    
        # POST /articles
        def create
          @article = Article.new(article_params)
          @article.categories.clear
          @article.user = current_user
          
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @article.categories << Category.find(id)
            end
          end
    
          if @article.save
            redirect_to naturesoft_articles.edit_admin_article_path(@article.id), notice: 'Article was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /articles/1
        def update
          @article.categories.clear
          
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @article.categories << Category.find(id)
            end
          end
          
          if @article.update(article_params)
            redirect_to naturesoft_articles.edit_admin_article_path(@article.id), notice: 'Article was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /articles/1
        def destroy
          @article.destroy
          render text: 'Article was successfully destroyed.'
        end
        
        #CHANGE APPROVE /articles
        def approve
          @article.approve
          render text: 'Article was successfully approved.'
        end
        
        def disapprove
          @article.disapprove
          render text: 'Article was successfully disapproved.'
        end
        
        #CHANGE STATUS /articles
        def enable
          @article.enable
          render text: 'Article was successfully active.'
        end
        
        def disable
          @article.disable
          render text: 'Article was successfully inactive.'
        end
        
        # DELETE /articles/delete?ids=1,2,3
        def delete
          @articles = Article.where(id: params[:ids].split(","))
          @articles.destroy_all
          render text: 'Article(s) was successfully destroyed.'
        end
        
        # GET /articles/select2
        def select2
          render json: Article.select2(params)
        end
        
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_article
            @article = Article.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def article_params
            params.fetch(:article, {}).permit(:image_url, :approved, :title, :content, :status, :image_id, :intro_text, :tags)
          end
      end
    end
  end
end

app/controllers/naturesoft/articles/admin/categories_controller.rb
module Naturesoft
  module Articles
    module Admin
      class CategoriesController < Naturesoft::Admin::AdminController
        before_action :set_category, only: [:show, :edit, :update, :enable, :disable, :destroy]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Article", naturesoft_articles.admin_categories_path
          add_breadcrumb "Categories", naturesoft_articles.admin_categories_path
        end
    
        # GET /categories
        def index
          @categories = Category.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("articles", "categories_items_per_page"))
        end
    
        # GET /categories/1
        def show
        end
    
        # GET /categories/new
        def new
          @category = Category.new
          add_breadcrumb "New Category", nil,  class: "active"
        end
    
        # GET /categories/1/edit
        def edit
          add_breadcrumb "Edit Category", nil,  class: "active"
        end
    
        # POST /categories
        def create
          @category = Category.new(category_params)
          @category.user = current_user
    
          if @category.save
            redirect_to naturesoft_articles.edit_admin_category_path(@category.id), notice: 'Category was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /categories/1
        def update
          if @category.update(category_params)
            redirect_to naturesoft_articles.edit_admin_category_path(@category.id), notice: 'Category was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /categories/1
        def destroy
          @category.destroy
          render text: 'Category was successfully destroyed.'
        end
        
        #CHANGE STATUS /categories
        def enable
          @category.enable
          render text: 'Category was successfully active.'
        end
        
        def disable
          @category.disable
          render text: 'Category was successfully inactive.'
        end
        
        # DELETE /categories/delete?ids=1,2,3
        def delete
          @categories = Category.where(id: params[:ids].split(","))
          @categories.destroy_all
          render text: 'Category(s) was successfully destroyed.'
        end
        
        # GET /categories/select2
        def select2
          render json: Category.select2(params)
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_category
            @category = Category.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def category_params
            params.fetch(:category, {}).permit(:name, :description, :status, :parent_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/articles/admin/options_controller.rb
module Naturesoft
  module Articles
    module Admin
      class OptionsController < Naturesoft::Admin::AdminController
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Articles", naturesoft_articles.admin_articles_path
        end
    
        # GET /update
        def update
          add_breadcrumb "Settings", nil
          
          @options = Naturesoft::Option.options("articles")
        end
      end
    end
  end
end

app/controllers/naturesoft/articles/articles_controller.rb
module Naturesoft
  module Articles
    class ArticlesController < Naturesoft::FrontendController
      before_action :get_article, only: [:detail]
      before_action :get_category, only: [:listing, :faq]
      
      def about_us
      end
      
      def listing
        @articles = Article.search_frontend(params).paginate(:page => params[:page], :per_page => 5)
      end
      
      def detail
      end
      
      def faq
      end
      
      private
        def get_article
          @article = Naturesoft::Articles::Article.find(params[:blog_id])
        end
        
        def get_category
          @category = params[:cat_id].present? ? Naturesoft::Articles::Category.find(params[:cat_id]) : nil
        end
    end
  end
end

app/controllers/naturesoft/articles/backend/articles_controller.rb
module Naturesoft
  module Articles
    module Backend
      class ArticlesController < Naturesoft::Backend::BackendController
        before_action :set_article, only: [:show, :edit, :update, :approve, :disapprove, :enable, :disable, :destroy]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Article", naturesoft_articles.backend_articles_path
          add_breadcrumb "Articles", naturesoft_articles.backend_articles_path
        end
    
        # GET /articles
        def index
          @articles = Article.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("articles", "items_per_page"))
        end
    
        # GET /articles/1
        def show
        end
    
        # GET /articles/new
        def new
          @article = Article.new
          add_breadcrumb "New Article", nil,  class: "active"
        end
    
        # GET /articles/1/edit
        def edit
          add_breadcrumb "Edit Article", nil,  class: "active"
        end
    
        # POST /articles
        def create
          @article = Article.new(article_params)
          @article.categories.clear
          @article.user = current_user
          
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @article.categories << Category.find(id)
            end
          end
    
          if @article.save
            redirect_to naturesoft_articles.edit_backend_article_path(@article.id), notice: 'Article was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /articles/1
        def update
          @article.categories.clear
          
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @article.categories << Category.find(id)
            end
          end
          
          if @article.update(article_params)
            redirect_to naturesoft_articles.edit_backend_article_path(@article.id), notice: 'Article was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /articles/1
        def destroy
          @article.destroy
          render text: 'Article was successfully destroyed.'
        end
        
        #CHANGE APPROVE /articles
        def approve
          @article.approve
          render text: 'Article was successfully approved.'
        end
        
        def disapprove
          @article.disapprove
          render text: 'Article was successfully disapproved.'
        end
        
        #CHANGE STATUS /articles
        def enable
          @article.enable
          render text: 'Article was successfully active.'
        end
        
        def disable
          @article.disable
          render text: 'Article was successfully inactive.'
        end
        
        # DELETE /articles/delete?ids=1,2,3
        def delete
          @articles = Article.where(id: params[:ids].split(","))
          @articles.destroy_all
          render text: 'Article(s) was successfully destroyed.'
        end
        
        # GET /articles/select2
        def select2
          render json: Article.select2(params)
        end
        
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_article
            @article = Article.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def article_params
            params.fetch(:article, {}).permit(:image_url, :approved, :title, :content, :status, :image_id, :intro_text, :tags)
          end
      end
    end
  end
end

app/controllers/naturesoft/articles/backend/options_controller.rb
module Naturesoft
  module Articles
    module Backend
      class OptionsController < Naturesoft::Backend::BackendController
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Articles", naturesoft_articles.backend_articles_path
        end
    
        # GET /update
        def update
          add_breadcrumb "Settings", nil
          
          @options = Naturesoft::Option.options("articles")
        end
      end
    end
  end
end

app/controllers/naturesoft/articles/categories_controller.rb
module Naturesoft
  module Articles
    class CategoriesController < Naturesoft::FrontendController
      before_action :get_category, only: [:newest_article]
      
      def newest_article
        @article = @category.get_newest_article
      end
      
      private
      def get_category
        @category = Naturesoft::Articles::Category.find(params[:id])
      end
    end
  end
end

app/helpers/naturesoft/articles/application_helper.rb
module Naturesoft
  module Articles
    module ApplicationHelper
    end
  end
end

app/views/naturesoft/articles/backend/articles/_form.html.erb
<% if article.errors.any? %>
  <div class="alert alert-warning alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
  
      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for([naturesoft_articles, :backend, article], html: {class: "form-horizontal validate", multipart: true}) do |f| %>

    <div class="form-group">
      <label class="col-md-2 control-label" ><%= t(:image) %> <span class='text-danger'>*</span></label>
      <div class="media no-margin-top col-md-10">
        <div class="media-left">
          <%= image_tag(image_src(article.image_url.system), class: "",  "preview-for": "article[image_url]") %>
        </div>
  
        <div class="media-body">
          <input type="file" name="article[image_url]" class="file-styled previewable">
          <span class="help-block">Accepted formats: gif, png, jpg.</span>
        </div>
      </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:title) %> <span class='text-danger'>*</span></label>
        <div class="col-md-10">
            <%= f.text_field :title, class: "form-control required" %>
        </div>
    </div>
        
    <div class="form-group field">
        <label class="col-md-2 control-label" ><%= t(:category) %> <span class='text-danger'>*</span></label>
        <div class="col-md-10">
          <div class="input-group">
            <% selected = options_for_select((article.categories.map {|c| [c.name, c.id]}),article.categories.map(&:id)) %>
            <%= select_tag("category_ids[]",
              selected,
              {
                class: "select2-ajax required",
                include_blank: "none",
                multiple: "multiple",
                "data-url": select2_backend_categories_path,
              }
            ) %>
            <span class="input-group-btn">
              <a class="btn btn-info" href="<%= naturesoft_articles.new_backend_category_path %>"><i class="icon-plus2"></i></a>
            </span>
          </div>
        </div>
    </div>
    
    <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:intro_text) %> <span class='text-danger'>*</span></label>
        <div class="col-md-10">
            <%= f.text_area :intro_text, class: "form-control required" %>
        </div>
    </div>
        
    <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:content) %> <span class='text-danger'>*</span></label>
    </div>
    
    <div class="form-group">
        <div class="col-md-12">
            <%= f.text_area :content, rows: "4", cols: "4", class: "editor" %>
        </div>
    </div>
        
    <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:tags) %> </label>
        <div class="col-md-10">
            <%= f.text_field :tags, class: "form-control" %>
        </div>
    </div>

    <div class="text-right">
        <%= button_tag "#{t(:save)} <i class=\"icon-plus22 position-right\"></i>".html_safe, class: "btn btn-primary"%>
    </div>
    
<% end %>

app/views/naturesoft/articles/backend/articles/edit.html.erb
<% title t(:edit_article) + ": " + @article.title %>

<!-- Horizontal form options -->
<div class="row">
    <div class="col-md-12">

        <!-- Basic layout-->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><%= t(:edit_article) %></h5>
            </div>
            
            <div class="panel-body">
                <%= render 'form', article: @article %>
            </div>

        </div>
        <!-- /basic layout -->
    </div>
</div>
<!-- /horizontal form options -->

app/views/naturesoft/articles/backend/articles/index.html.erb
<% title t(:articles) %>

<div class="page_actions">
    <%= link_to "#{t(:new_article)} <i class=\"icon-plus22 position-right\"></i>".html_safe, naturesoft_articles.new_backend_article_path, class: 'btn btn-primary' %>
</div>
<br />

<form class="listing-form">
    
    <div class="panel panel-flat border-top-primary">
        <div class="panel-body filter-box">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:sort_by) %></label>
                        <%= select_tag(:sort_by, options_for_select(Naturesoft::Articles::Article.sort_by, :selected => params[:sort_by]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:sort_order) %></label>
                        <%= select_tag(:sort_orders, options_for_select(Naturesoft::Articles::Article.sort_orders, :selected => params[:sort_orders]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:status) %></label>
                        <%= select_tag(:status, options_for_select(Naturesoft::Articles::Article.status, :selected => params[:status]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group has-feedback">
                        <label><%= t(:search) %></label>
                        <input type="text" name="keyword" class="form-control" placeholder="Enter search..." value="<%= params[:keyword] %>">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-size-base"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
	
	<div class="btn-group list_actions mb-10 hide">
        <button type="button" class="btn btn-xs btn-info dropdown-toggle" data-toggle="dropdown">
            Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">											
            <li>
                <a href="" data-href="<%= naturesoft_articles.delete_backend_articles_path %>" data-confirm="Are you sure!" data-method="DELETE">
                    <i class="icon-enter"></i> Delete
                </a>
            </li>            
        </ul>
    </div>
                
    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="table-container">
            <table class="table">
                <thead>
                    <tr class="bg-teal-800">
						<th width="1%" class="check_all_list">
                            <input type="checkbox" class="styled">
                        </th>
                        <th><%= t(:image) %></th>
                        <th><%= t(:title) %></th>
                        <td class="text-center"><%= t(:creator) %></td>
                        <th><%= t(:created_at) %></th>
						<th><%= t(:status) %></th>
                        <th class="text-center"><%= t(:actions) %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @articles.each do |item| %>
                        <tr<% if item.approved == true %> class="success"<% end %><% if item.approved == false %> class="warning"<% end %>>
                            <td width="1%">
                                <input type="checkbox" class="node styled"
                                    name="ids[]"
                                    value="<%= item.id %>"
                                />
                            </td>
							<td>
								<a href="<%= naturesoft_articles.edit_backend_article_path(item) %>"><%= image_tag(image_src(item.image_url), size: "70x70", class: "img-rounded img-preview") %></a>
							</td>
                            <td class="kp_search">
                                <%= item.title %>                                
                            </td>
                            <td class="text-center"><%= user_box(item.user) %></td>
                            <td><%= item.created_at.strftime("%d/%m/%Y") %></td>
							<td><%= display_status(item.status) %></td>
                            <td class="text-center">
                                <div class="btn-group">
                                    <%= link_to '<i class="icon-pencil"></i>'.html_safe, naturesoft_articles.edit_backend_article_path(item), class: "btn bg-teal btn-icon btn-xs", title: item.title %>
                                    <button type="button" class="btn bg-teal dropdown-toggle btn-xs" data-toggle="dropdown"><span class="caret"></span></button>
                                    <ul class="dropdown-menu dropdown-menu-right">
                                        <% if item.approved == false %>
                                        <li>
                                            <%= link_to '<i class="glyphicon glyphicon-ok"></i> '.html_safe + t(:approve), naturesoft_articles.approve_backend_articles_path(id: item.id), method: :put %>
                                        </li>
                                        <% end %>
                                        <% if item.approved == true %>
                                        <li>
                                            <%= link_to '<i class="glyphicon glyphicon-remove"></i> '.html_safe + t(:disapprove), naturesoft_articles.disapprove_backend_articles_path(id: item.id), method: :put %>
                                        </li>
                                        <% end %>
                                    
                                        <% if item.status == "active" %>
                                        <li>
                                            <%= link_to '<i class="icon-lock4"></i> '.html_safe + t(:inactive), naturesoft_articles.disable_backend_articles_path(id: item.id), method: :put %>
                                        </li>
                                        <% end %>
                                        <% if item.status == "inactive" %>
                                        <li>
                                            <%= link_to '<i class="icon-unlocked"></i> '.html_safe + t(:active), naturesoft_articles.enable_backend_articles_path(id: item.id), method: :put %>
                                        </li>
                                        <% end %>
                                    
                                        <li>
                                            <%= link_to '<i class="icon-cross2"></i> '.html_safe + t(:delete), naturesoft_articles.backend_article_path(item), method: :delete, data: {confirm: 'Are you sure?'} %>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="dataTables_wrapper no-footer">
                <div class="datatable-footer showed">
                    <div class="dataTables_info" ><%= page_entries_info @articles %></div>
                    <div class="dataTables_paginate paging_simple_numbers">
                        <%= will_paginate @articles, previous_label: '←', next_label: '→', renderer: BootstrapPagination::Rails %>
                    </div>
                </div>
            </div>
		  </div>
        </div>
    </div>
</form>

<!-- /basic datatable -->

app/views/naturesoft/articles/backend/articles/new.html.erb
<% title t(:new_article) %>

<!-- Horizontal form options -->
<div class="row">
    <div class="col-md-12">

        <!-- Basic layout-->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><%= t(:new_article) %></h5>
            </div>
            
            <div class="panel-body">
                <%= render 'form', article: @article %>
            </div>

        </div>
        <!-- /basic layout -->
    </div>
</div>
<!-- /horizontal form options -->

app/views/naturesoft/articles/backend/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>