config/routes.rb
Naturesoft::Articles::Engine.routes.draw do
  namespace :backend, module: "backend", path: "backend/content" do
    resources :articles do
      collection do
        put "approve"
        put "disapprove"
        put "enable"
        put "disable"
        delete 'delete'
        get 'select2'
      end
    end
    resources :categories do
      collection do
        put "enable"
        put "disable"
        delete 'delete'
        get "select2"
      end
    end
  end
end

app/models/naturesoft/articles/category.rb
module Naturesoft::Articles
  class Category < ApplicationRecord
		validates :name, presence: true
    
    belongs_to :user
    has_and_belongs_to_many :articles
    belongs_to :parent, class_name: "Category", optional: true
    has_many :children, class_name: "Category", foreign_key: "parent_id"
    after_save :update_level
    
    def update_level
      level = 1
			p = self.parent
			while !p.nil? do
				level += 1
				p = p.parent
			end
			self.update_column(:level, level)
    end
    
    def self.sort_by
      [
			  ["Level","naturesoft_articles_categories.level"],
        ["Name","naturesoft_articles_categories.name"],
        ["Created At","naturesoft_articles_categories.created_at"]
      ]
    end
    def self.sort_orders
      [
        ["ASC","asc"],
        ["DESC","desc"]
      ]
    end
    
    #Filter, Sort
    def self.search(params)
      records = self.all
      
      #Search keyword filter
      if params[:keyword].present?
        params[:keyword].split(" ").each do |k|
          records = records.where("LOWER(CONCAT(naturesoft_articles_categories.name,' ',naturesoft_articles_categories.description)) LIKE ?", "%#{k.strip.downcase}%") if k.strip.present?
        end
      end
      
      # Parent category
      if params[:parent_id].present?
				records = records.where(parent_id: params[:parent_id])
      end
      
      # for sorting
      sort_by = params[:sort_by].present? ? params[:sort_by] : "naturesoft_articles_categories.name"
      sort_orders = params[:sort_orders].present? ? params[:sort_orders] : "asc"
      records = records.order("#{sort_by} #{sort_orders}")
      
      return records
    end
    
    # change status
    def enable
			update_columns(status: "active")
		end
    
    def disable
			update_columns(status: "inactive")
		end
    
    # get categories by level
    def self.get_by_level(lvl)
			self.where(level: 1)
		end
    
    def get_all_related_ids
      arr = []
      arr << self.id
      self.children.each do |i1|
          arr << i1.id
          i1.children.each do |i2|
              arr << i2.id
              i2.children.each do |i3|
                  arr << i3.id
              end
          end 
      end
      return arr
		end
    
    # get article for category
    def get_newest_article
			record = Naturesoft::Articles::Article.joins(:categories).where(naturesoft_articles_categories: {id: self.get_all_related_ids}).uniq
			return record.last
    end

    # display name with parent
    def full_name
			names = [self.name]
			p = self.parent
			while !p.nil? do
				names << p.name
				p = p.parent
			end
			names.reverse.join(" >> ")
		end
    
    # data for select2 ajax
    def self.select2(params)
			items = self.search(params).order("level")
			if params[:excluded].present?
				items = items.where.not(id: params[:excluded].split(","))
			end
			options = [{"id" => "", "text" => "none"}]
			options += items.map { |c| {"id" => c.id, "text" => c.full_name} }
			result = {"items" => options}
		end
    
    def self.get_all_categories
			self.where(status: 'active')
		end
    
  end
end

app/controllers/naturesoft/articles/admin/categories_controller.rb
module Naturesoft
  module Articles
    module Admin
      class CategoriesController < Naturesoft::Admin::AdminController
        before_action :set_category, only: [:show, :edit, :update, :enable, :disable, :destroy]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Article", naturesoft_articles.admin_categories_path
          add_breadcrumb "Categories", naturesoft_articles.admin_categories_path
        end
    
        # GET /categories
        def index
          @categories = Category.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("articles", "categories_items_per_page"))
        end
    
        # GET /categories/1
        def show
        end
    
        # GET /categories/new
        def new
          @category = Category.new
          add_breadcrumb "New Category", nil,  class: "active"
        end
    
        # GET /categories/1/edit
        def edit
          add_breadcrumb "Edit Category", nil,  class: "active"
        end
    
        # POST /categories
        def create
          @category = Category.new(category_params)
          @category.user = current_user
    
          if @category.save
            redirect_to naturesoft_articles.edit_admin_category_path(@category.id), notice: 'Category was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /categories/1
        def update
          if @category.update(category_params)
            redirect_to naturesoft_articles.edit_admin_category_path(@category.id), notice: 'Category was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /categories/1
        def destroy
          @category.destroy
          render text: 'Category was successfully destroyed.'
        end
        
        #CHANGE STATUS /categories
        def enable
          @category.enable
          render text: 'Category was successfully active.'
        end
        
        def disable
          @category.disable
          render text: 'Category was successfully inactive.'
        end
        
        # DELETE /categories/delete?ids=1,2,3
        def delete
          @categories = Category.where(id: params[:ids].split(","))
          @categories.destroy_all
          render text: 'Category(s) was successfully destroyed.'
        end
        
        # GET /categories/select2
        def select2
          render json: Category.select2(params)
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_category
            @category = Category.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def category_params
            params.fetch(:category, {}).permit(:name, :description, :status, :parent_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/articles/backend/articles_controller.rb
module Naturesoft
  module Articles
    module Backend
      class ArticlesController < Naturesoft::Backend::BackendController
        before_action :set_article, only: [:show, :edit, :update, :approve, :disapprove, :enable, :disable, :destroy]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Article", naturesoft_articles.backend_articles_path
          add_breadcrumb "Articles", naturesoft_articles.backend_articles_path
        end
    
        # GET /articles
        def index
          @articles = Article.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("articles", "items_per_page"))
        end
    
        # GET /articles/1
        def show
        end
    
        # GET /articles/new
        def new
          @article = Article.new
          add_breadcrumb "New Article", nil,  class: "active"
        end
    
        # GET /articles/1/edit
        def edit
          add_breadcrumb "Edit Article", nil,  class: "active"
        end
    
        # POST /articles
        def create
          @article = Article.new(article_params)
          @article.categories.clear
          @article.user = current_user
          
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @article.categories << Category.find(id)
            end
          end
    
          if @article.save
            redirect_to naturesoft_articles.edit_backend_article_path(@article.id), notice: 'Article was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /articles/1
        def update
          @article.categories.clear
          
          if params[:category_ids].present?
            params[:category_ids].each do |id|      
              @article.categories << Category.find(id)
            end
          end
          
          if @article.update(article_params)
            redirect_to naturesoft_articles.edit_backend_article_path(@article.id), notice: 'Article was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /articles/1
        def destroy
          @article.destroy
          render text: 'Article was successfully destroyed.'
        end
        
        #CHANGE APPROVE /articles
        def approve
          @article.approve
          render text: 'Article was successfully approved.'
        end
        
        def disapprove
          @article.disapprove
          render text: 'Article was successfully disapproved.'
        end
        
        #CHANGE STATUS /articles
        def enable
          @article.enable
          render text: 'Article was successfully active.'
        end
        
        def disable
          @article.disable
          render text: 'Article was successfully inactive.'
        end
        
        # DELETE /articles/delete?ids=1,2,3
        def delete
          @articles = Article.where(id: params[:ids].split(","))
          @articles.destroy_all
          render text: 'Article(s) was successfully destroyed.'
        end
        
        # GET /articles/select2
        def select2
          render json: Article.select2(params)
        end
        
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_article
            @article = Article.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def article_params
            params.fetch(:article, {}).permit(:image_url, :approved, :title, :content, :status, :image_id, :intro_text, :tags)
          end
      end
    end
  end
end

app/controllers/naturesoft/articles/backend/categories_controller.rb
module Naturesoft
  module Articles
    module Backend
      class CategoriesController < Naturesoft::Backend::BackendController
        before_action :set_category, only: [:show, :edit, :update, :enable, :disable, :destroy]
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Article", naturesoft_articles.backend_categories_path
          add_breadcrumb "Categories", naturesoft_articles.backend_categories_path
        end
    
        # GET /categories
        def index
          @categories = Category.search(params).paginate(:page => params[:page], :per_page => Naturesoft::Option.get("articles", "categories_items_per_page"))
        end
    
        # GET /categories/1
        def show
        end
    
        # GET /categories/new
        def new
          @category = Category.new
          add_breadcrumb "New Category", nil,  class: "active"
        end
    
        # GET /categories/1/edit
        def edit
          add_breadcrumb "Edit Category", nil,  class: "active"
        end
    
        # POST /categories
        def create
          @category = Category.new(category_params)
          @category.user = current_user
    
          if @category.save
            redirect_to naturesoft_articles.edit_backend_category_path(@category.id), notice: 'Category was successfully created.'
          else
            render :new
          end
        end
    
        # PATCH/PUT /categories/1
        def update
          if @category.update(category_params)
            redirect_to naturesoft_articles.edit_backend_category_path(@category.id), notice: 'Category was successfully updated.'
          else
            render :edit
          end
        end
    
        # DELETE /categories/1
        def destroy
          @category.destroy
          render text: 'Category was successfully destroyed.'
        end
        
        #CHANGE STATUS /categories
        def enable
          @category.enable
          render text: 'Category was successfully active.'
        end
        
        def disable
          @category.disable
          render text: 'Category was successfully inactive.'
        end
        
        # DELETE /categories/delete?ids=1,2,3
        def delete
          @categories = Category.where(id: params[:ids].split(","))
          @categories.destroy_all
          render text: 'Category(s) was successfully destroyed.'
        end
        
        # GET /categories/select2
        def select2
          render json: Category.select2(params)
        end
    
        private
          # Use callbacks to share common setup or constraints between actions.
          def set_category
            @category = Category.find(params[:id])
          end
    
          # Only allow a trusted parameter "white list" through.
          def category_params
            params.fetch(:category, {}).permit(:name, :description, :status, :parent_id)
          end
      end
    end
  end
end

app/controllers/naturesoft/articles/backend/options_controller.rb
module Naturesoft
  module Articles
    module Backend
      class OptionsController < Naturesoft::Backend::BackendController
        before_action :default_breadcrumb
        
        # add top breadcrumb
        def default_breadcrumb
          add_breadcrumb "Articles", naturesoft_articles.backend_articles_path
        end
    
        # GET /update
        def update
          add_breadcrumb "Settings", nil
          
          @options = Naturesoft::Option.options("articles")
        end
      end
    end
  end
end

app/controllers/naturesoft/articles/categories_controller.rb
module Naturesoft
  module Articles
    class CategoriesController < Naturesoft::FrontendController
      before_action :get_category, only: [:newest_article]
      
      def newest_article
        @article = @category.get_newest_article
      end
      
      private
      def get_category
        @category = Naturesoft::Articles::Category.find(params[:id])
      end
    end
  end
end

app/views/naturesoft/articles/backend/categories/_form.html.erb
<% if category.errors.any? %>
  <div class="alert alert-warning alert-bordered">
    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>
  
      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_for([naturesoft_articles, :backend, category], html: {class: "form-horizontal validate"}) do |f| %>
    
    <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:name) %> <span class='text-danger'>*</span></label>
        <div class="col-md-10">
            <%= f.text_field :name, class: "form-control required" %>
        </div>
    </div>
        
    <div class="form-group">
        <label class="col-md-2 control-label" ><%= t(:description) %> <!--<span class='text-danger'>*</span>--></label>
        <div class="col-md-10">
            <%= f.text_area :description, rows: "5", cols: "5", class: "form-control" %>
        </div>
    </div>
        
    <div class="form-group">
      <label class="col-md-2 control-label" ><%= t(:parent_category) %></label>
        <div class="col-md-10">
            <%= select_tag("category[parent_id]",
              nil,
              {
                class: "select2-ajax",
                "data-url": select2_backend_categories_path,
                "data-excluded": category.id,
                "value": category.parent.present? ? category.parent.id : "",
                "text": category.parent.present? ? category.parent.name : ""
              }
          ) %>
        </div>
    </div>

    <div class="text-right">
        <%= button_tag "#{t(:save)} <i class=\"icon-plus22 position-right\"></i>".html_safe, class: "btn btn-primary"%>
    </div>
    
<% end %>

app/views/naturesoft/articles/backend/categories/edit.html.erb
<% title t(:edit_article_category) + ": " + @category.name %>

<!-- Horizontal form options -->
<div class="row">
    <div class="col-md-12">

        <!-- Basic layout-->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><%= t(:edit_category) %></h5>
            </div>
            
            <div class="panel-body">
                <%= render 'form', category: @category %>
            </div>

        </div>
        <!-- /basic layout -->
    </div>
</div>
<!-- /horizontal form options -->

app/views/naturesoft/articles/backend/categories/index.html.erb
<% title t(:categories) %>

<div class="page_actions">
    <%= link_to "#{t(:new_category)} <i class=\"icon-plus22 position-right\"></i>".html_safe, naturesoft_articles.new_backend_category_path, class: 'btn btn-primary' %>
</div>
<br />

<form class="listing-form">
    
    <div class="panel panel-flat border-top-primary">
        <div class="panel-body filter-box">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:parent) %></label>
                        <%= select_tag(:parent_id, [], class: "select2-ajax", "data-url": select2_backend_categories_path) %>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label><%= t(:sort_by) %></label>
                        <%= select_tag(:sort_by, options_for_select(Naturesoft::Articles::Category.sort_by, :selected => params[:sort_by]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label><%= t(:sort_order) %></label>
                        <%= select_tag(:sort_orders, options_for_select(Naturesoft::Articles::Category.sort_orders, :selected => params[:sort_orders]), class: "select2") %>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group has-feedback">
                        <label><%= t(:search) %></label>
                        <input type="text" name="keyword" class="form-control" placeholder="Enter search(name, description)..." value="<%= params[:keyword] %>">
                        <div class="form-control-feedback">
                            <i class="icon-search4 text-size-base"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
            
    <div class="btn-group list_actions mb-10 hide">
        <button type="button" class="btn btn-xs btn-info dropdown-toggle" data-toggle="dropdown">
            Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">											
            <li>
                <a href="" data-href="<%= naturesoft_articles.delete_backend_articles_path %>" data-confirm="Are you sure!" data-method="DELETE">
                    <i class="icon-enter"></i> Delete
                </a>
            </li>            
        </ul>
    </div>
                
    <!-- Basic datatable -->
    <div class="panel panel-flat">
        <div class="table-container">
            <table class="table">
                <thead>
                    <tr class="bg-teal-800">
                        <th width="1%" class="check_all_list">
                            <input type="checkbox" class="styled">
                        </th>
                        <th><%= t(:title) %></th>
                        <th><%= t(:description) %></th>                        
                        <td class="text-center"><%= t(:creator) %></td>
                        <th><%= t(:created_at) %></th>
                        <th><%= t(:status) %></th>
                        <th class="text-right"><%= t(:actions) %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |item| %>
                        <tr>
                            <td width="1%">
                                <input type="checkbox" class="node styled"
                                    name="ids[]"
                                    value="<%= item.id %>"
                                />
                            </td>
                            <td class="kq_search">
                                <%= link_to item.full_name, naturesoft_articles.edit_backend_category_path(item), class: "text-semibold" %>                              
                            </td>
                            <td class="kq_search"><%= truncate(strip_tags(item.description), length: 150) %></td>                                                        
                            <td class="text-center"><%= user_box(item.user) %></td>
                            <td><%= display_date(item.created_at) %></td>
                            <td><%= display_status(item.status) %></td>
                            <td class="text-right">
                                <div class="btn-group">
                                    <ul class="icons-list">
                                        <%= link_to '<i class="icon-pencil"></i>'.html_safe, naturesoft_articles.edit_backend_category_path(item), class: "btn bg-teal btn-icon btn-xs", title: item.name %>
                                        <button type="button" class="btn bg-teal dropdown-toggle btn-xs" data-toggle="dropdown"><span class="caret"></span></button>
                                        <ul class="dropdown-menu dropdown-menu-right">
                                            <% if item.status == "active" %>
                                            <li>
                                                <%= link_to '<i class="icon-lock4"></i> '.html_safe + t(:inactive), naturesoft_articles.disable_backend_categories_path(id: item.id), method: :put %>
                                            </li>
                                            <% end %>
                                            <% if item.status == "inactive" %>
                                            <li>
                                                <%= link_to '<i class="icon-unlocked"></i> '.html_safe + t(:active), naturesoft_articles.enable_backend_categories_path(id: item.id), method: :put %>
                                            </li>
                                            <% end %>
                                            <li>
                                                <%= link_to '<i class="icon-cross2"></i> '.html_safe + t(:delete), naturesoft_articles.backend_category_path(item), method: :delete, data: {confirm: 'Are you sure?'} %>
                                            </li>
                                        </ul>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <div class="dataTables_wrapper no-footer">
                <div class="datatable-footer showed">
                    <div class="dataTables_info" ><%= page_entries_info @categories %></div>
                    <div class="dataTables_paginate paging_simple_numbers">
                        <%= will_paginate @categories, previous_label: '←', next_label: '→', renderer: BootstrapPagination::Rails %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<!-- /basic datatable -->

app/views/naturesoft/articles/backend/categories/new.html.erb
<% title t(:new_article_category) %>

<!-- Horizontal form options -->
<div class="row">
    <div class="col-md-12">

        <!-- Basic layout-->
        <div class="panel panel-flat">
            <div class="panel-heading">
                <h5 class="panel-title"><%= t(:new_category) %></h5>
            </div>
            
            <div class="panel-body">
                <%= render 'form', category: @category %>
            </div>

        </div>
        <!-- /basic layout -->
    </div>
</div>
<!-- /horizontal form options -->

app/views/naturesoft/articles/backend/categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_category_path(@article_category) %> |
<%= link_to 'Back', article_categories_path %>